// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCozDfDWpGpgs9RSf5VKTICi61y9XmYf9M',
    appId: '1:841395424750:web:2ce90450b0c7efd10ad2ff',
    messagingSenderId: '841395424750',
    projectId: 'mechtec-app',
    authDomain: 'mechtec-app.firebaseapp.com',
    storageBucket: 'mechtec-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl0q4lXObbWyko3O8OwXPjOhBtt0oQbfk',
    appId: '1:841395424750:android:e9983c7c359508090ad2ff',
    messagingSenderId: '841395424750',
    projectId: 'mechtec-app',
    storageBucket: 'mechtec-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD6Nn9p9O8CsBw8YwKHIKKJp1MfMmKTAE',
    appId: '1:841395424750:ios:3019f6d324e8a55f0ad2ff',
    messagingSenderId: '841395424750',
    projectId: 'mechtec-app',
    storageBucket: 'mechtec-app.appspot.com',
    iosBundleId: 'com.example.widgetassignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD6Nn9p9O8CsBw8YwKHIKKJp1MfMmKTAE',
    appId: '1:841395424750:ios:3019f6d324e8a55f0ad2ff',
    messagingSenderId: '841395424750',
    projectId: 'mechtec-app',
    storageBucket: 'mechtec-app.appspot.com',
    iosBundleId: 'com.example.widgetassignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCozDfDWpGpgs9RSf5VKTICi61y9XmYf9M',
    appId: '1:841395424750:web:a0a85421ac225e930ad2ff',
    messagingSenderId: '841395424750',
    projectId: 'mechtec-app',
    authDomain: 'mechtec-app.firebaseapp.com',
    storageBucket: 'mechtec-app.appspot.com',
  );

}